### ISSUE TITLE
Found a plagiarize code..?

### ISSUE THREAD

**Issue by rurimo** [mrcsxsiq/Kotlin-Pokedex#14]
I found this repository and it seems the owner changed and removed every copyright from the sources.

https://github.com/thinktocode/PokeDex

I've made an issue for arranging the problem, but I've got a block from the owner. 😭

**Comment by DDriggs00** [comment]
This code is MIT licensed. It's impossible to plagiarize it, since the license specifies that any and all use is okay.

**Comment by rurimo** [comment]
Thanks for explaining!
