### ISSUE TITLE
Jetpack compose

### ISSUE THREAD

**Issue by francismariano** [mrcsxsiq/Kotlin-Pokedex#4]
Hello @mrcsxsiq . Nice job, congrats man.

Lets to add jetpack compose in some screens. It is a new concept and would be very interesting to see it works in a real application.

**Comment by zsoltk** [comment]
Hey @mrcsxsiq! I got inspired by your project and its Flutter counterpart when I first saw them, and started working on a Compose version myself which I just published at: https://github.com/zsoltk/compose-pokedex. Our approaches are different, I intended to play around completely without Fragments, with Compose as a single-Activity approach, so I guess it makes sense to have both of these projects as separate ones. Nevertheless, I added a link back to your repo. Keep it up!

**Comment by mrcsxsiq** [comment]
@francismariano Thank you. I hope this project helps you in any way.

**Comment by mrcsxsiq** [comment]
@zsoltk It's amazing. I'll add your project in readme too. Let's rock
